### ISSUE TITLE
dear 더보기 버튼

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#111]
무한스크롤로는 나중에.

**Comment by helloheesu** [comment]
#114 참고, 문제(사진) 원인 확인하기
![received.result](https://cloud.githubusercontent.com/assets/5011544/12052687/d933bdea-af54-11e5-92e5-2b1e6eb57341.png)
![rendered dear - 마지막의 이상한 데이터가 name값 undefined 나오는 것](https://cloud.githubusercontent.com/assets/5011544/12052688/da66d1d4-af54-11e5-83c8-b33a945146c1.png)

**Comment by outofmap** [comment]
@helloheesu 어떤 상황에서 이렇게 되나요?  일단 저는 dear가 6개있는 상태에서 저 문제가 나타나지 않고 있어요ㅜㅜ 
![2015-12-31 12 59 58](https://cloud.githubusercontent.com/assets/11879870/12053185/e94a4dac-af59-11e5-833d-4aa1dd10fbef.png)

희수가보내준 스샷에도 dear가 7개인 상황같은데, 어떤 조건에서 저러는지 알려주세요~
그리구 혹시 문제가 될수있는 코드를 수정해서 push 하긴했어요!!

**Comment by outofmap** [comment]
@helloheesu 저는 다른 문제를 만났는데요. 첫페이지에서 dearlist api상에서 placId가 0으로 가구있어서 다음과같은 에러가 발생했어요.
![2015-12-31 1 02 58](https://cloud.githubusercontent.com/assets/11879870/12053226/4c1ec548-af5a-11e5-9271-6b177164a52d.png)

**Comment by helloheesu** [comment]
일단 totalDearNum이 넘어오는 건 @outofmap 말대로 pull하니 해결됐습니다 ㅋㅋ.
placeId가 0으로 나타나는 건 새로운 에러! 끙아

**Comment by helloheesu** [comment]
@outofmap 이 제보한 건 069be3e 에서 해결!
