### ISSUE TITLE
API - GET postList 에서 isCut 알려주세요

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#115]

**Comment by helloheesu** [comment]
화면이 충분히 넓은 경우에, 서버에서 잘라준건지 글이 진짜로 저렇게 짧은지 알 수가 없어요.
그림 참조.
![충분히 넓은 화면](https://cloud.githubusercontent.com/assets/5011544/11977094/ab93cf02-a9c2-11e5-8206-221f3df2a772.png)
![좁은 화면](https://cloud.githubusercontent.com/assets/5011544/11977090/a75288a2-a9c2-11e5-98f3-3b81f3f9224b.png)

**Comment by outofmap** [comment]
지금은 DB에서 가져올때부터 LEFT(content, 50)으로 가져오고 있어요.
 이걸 해결하려면 생각해본 방법으로는
1. DB에서 내용전체를 가져와서 서버에서 자르고 원래 길이가 50이 넘는 것들은 표시를 해둔다. 
2. 프론트에 전체를 보내주고 프론트에서 자르고 자른 post는 표시를 해둔다.

**Comment by helloheesu** [comment]
프론트에서 max-width 를 한정해서 해결하기로!
몇 글자인지 세서 정하기!

모바일은 지금 크기 유지, 데스크탑에서도 편지지:dear목록 비율 유지해서 max-width 정하기

**Comment by helloheesu** [comment]
일단 80자로 자르고, 프론트에서는 그 미만 길이(50em)를 max-width로 정하겠습니다-
