### ISSUE TITLE
PlaceId에 맞게 dearlist가져오도록 하기

### ISSUE THREAD

**Issue by outofmap** [NHNNEXT/2015-01-WEB-TOITOITOI#123]
Post controller에서 client에 placeId 전달하기

**Comment by helloheesu** [comment]
해결되면 저도 알려주세요 jsp에 하드코딩했던 것 반영하겠습니닷

**Comment by helloheesu** [comment]
아. 기존 서버 코드는 잘 알려주고 있었어요.
1b0386b 에서 혹시나 하고 추가한, placeId를 중복해서 넘겨주는 코드는 제거해도 돼요.

다만 null일때에 대한 처리가 없었는데, 아래 포스트 목록이 `placeId = 1`인 것처럼 나오는 건 단순히 제가 `index.js`를 하드코딩했기 때문이었어요.
placeId가 유효한지 검사한후에 유효하지 않을 때에는 어떻게 할지 결정해야겠어요.
지금은 `isValidParameter`에서 이게 유효한 '숫자'인지만 검사하는데, existing placeId인지도 검사 필요-!

(+, 조금 더 자세한 상황 설명을 추가합니다)
place가 null, 즉 `placeId = 2`에 대한 요청이 오면 null을 보내고 jsp에서 해당 값이 필요한 부분들은 다 빈 문자열로 나와요. (아래 그림 참조, 장소 이름이 비어있음.)
![placeId=2](https://cloud.githubusercontent.com/assets/5011544/12005561/c6db5a36-abee-11e5-8eb1-963c146fa347.png)
