### ISSUE TITLE
like만들기 한 번 이상 like불가능  

### ISSUE THREAD

**Issue by outofmap** [NHNNEXT/2015-01-WEB-TOITOITOI#130]
새로고침 하기 전에는 like 다시 할 수 없게 하기.

**Comment by Kiboom** [comment]
like를 업데이트 하고나서 아무것도 리턴하지 않으니까,
그런 경우에는 누나가 위키에 올린 중국인 사이트에서 샘플코드 참고해서 작성하기.
작성하고 나면 postDao가 extends하고 있는 JdbcSupport를 지워버리기(?)

**Comment by Kiboom** [comment]
세션 고려해서ㅋㅋ 한 번 like하면 두 번 다시는 like 못하게 하기.

**Comment by helloheesu** [comment]
오잉 '새로고침'에 대한 건 클라에서 막으면 되는 거 아닌가욤???
서버에선 차라리 특정 ip에서 몇 초 이내에 너무 많이 오면 무시하기- 그런 게 더 필요하지 않....나?

**Comment by helloheesu** [comment]
프론트에서 막는걸로 이슈 변경할..까요......?

**Comment by Kiboom** [comment]
일단 그럼 새로고침에 대한 부분은 회의 때 정해보는거루 합시다~

**Comment by helloheesu** [comment]
프론트에서 버튼을 비활성화해서 막기로!
