### ISSUE TITLE
git push --force ?? PostDAO.java 의 커밋이 사라졌어요

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#132]
다음에도 이런 상황을 방지할 수 있도록, 푸쉬할 때 어떻게 했는지 상세하게 알려주세요.
이클립스가 똥으로 알려준다면 아예 터미널을 쓰고, 그게 아니라 경고 메시지를 무심코 지나친거라면 앞으로 주의하면 되니까요.

![내 커밋](https://cloud.githubusercontent.com/assets/5011544/12028507/7f3c421a-ae1b-11e5-9867-b9436014fa39.png)
![누가 먹었어](https://cloud.githubusercontent.com/assets/5011544/12028506/7dae0172-ae1b-11e5-9c53-c936dd6b5944.png)

**Comment by helloheesu** [comment]
아아 다음 커밋에서 해결이 된 거군요 ㅜㅜㅜ. 죄송합니다.
특정 커밋 기준에서 본 파일의 history를 보니까 사라져있었어요.

![다시 나타난 커밋](https://cloud.githubusercontent.com/assets/5011544/12028788/7e3091aa-ae20-11e5-9b32-ef19f42c1fad.png)

**Comment by outofmap** [comment]
아마 이때 상황이 git commit push하구나서 ㅜㅜ pull 안한걸 깨달아서 git stash 상태로 git pull -> conflict 해결 -> 다시 git stash pop했어요! 근데 맨첨에 git commit 까지했는지 push까지 했는지도 가물가물...
