### ISSUE TITLE
EmptyResultDataAccessException @APIFileController

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#142]
첫페이지에 예시로 둔 파일이, 저는 디비에 존재하지 않아서 에러가 납니다
예외처리 해주세욤~

![client](https://cloud.githubusercontent.com/assets/5011544/12077892/fb04124a-b23c-11e5-8f3e-8e25538eda4d.png)

![server](https://cloud.githubusercontent.com/assets/5011544/12077890/d07d3f38-b23c-11e5-8ef1-14b68c31a176.png)

**Comment by outofmap** [comment]
<img width="1145" alt="2016-01-03 11 54 49" src="https://cloud.githubusercontent.com/assets/11879870/12079257/a472a8d6-b275-11e5-96e9-0e0d49aec9fc.png">

**Comment by helloheesu** [comment]
해결되었으니 프론트에도 반영해야겠군요 assign myself 하겠습니다

**Comment by helloheesu** [comment]
@outofmap ㅜㅜ 지금보니 error message가 너무 길고 불친절해요.. 좀더 짧고 직관적인 메시지는 없을까요...?ㅜㅜ

**Comment by outofmap** [comment]
@helloheesu No file 뒤에 spring어쩌구를 아예빼버릴수도있어요. 저거는 서버에서 찍은 error로그 그대로인데 필요할까봐 client에 보낸거라서요. No file fh만 가게 할까요??

**Comment by helloheesu** [comment]
@outofmap  흠 네. 무슨 파일이 없는건지 같은건 필요없겠죠?? 저게 한글로 표현하면 무슨 상황인거지......

**Comment by outofmap** [comment]
@helloheesu  요청하신 이미지가 없습니다. error message 를 한글로 (유저에게 바로 보여줄수 있을정도로 정리한 메시지로) 보내주는게 희수가 더 편한가요?!!그러면 그렇게할게요!

**Comment by helloheesu** [comment]
프론트에 아직 반영 안 돼서 오픈!

**Comment by helloheesu** [comment]
가 아니라 반영돼있음! (유효하지 않은 src등의 이유로) 이미지 로드 실패하면 아예 렌더하지 않음.
