### ISSUE TITLE
reply 정렬 기준이.. 생성타임이 아니고 수정타임 ㅜㅜ

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#154]
timestamp 타입은 update시에 갱신됩니다..ㅜㅠ

**Comment by outofmap** [comment]
각자의 db에서 
ALTER TABLE reply CHANGE createdtime createdtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
실행해주세여...실서버는 이미 고침! :)

**Comment by helloheesu** [comment]
감사합니다 실행했습니다~
븉퇴 로컬과 실서버에도 돼 있는지 확인하시고 close해주시면 감사하겠습니다~~
