### ISSUE TITLE
Dear 서비스 만든이

### ISSUE THREAD

**Issue by outofmap** [NHNNEXT/2015-01-WEB-TOITOITOI#163]
의견취합할 수 있게 하기
- Dear. 만든이 더미 데이터 하나 만들어주기
- preview 보내줄 때 만든이는 제외하고 보내주기
- 프론트에선 static하게 고정해두고 색 다르게

**Comment by helloheesu** [comment]
@Kiboom  다 된거죠? 클로즈 해주세요- 마일스톤 백프로를 향해!ㅋㅋ
