### ISSUE TITLE
3 dear 테이블에 postNum 필드 추가 (페이지 개수 알기 편함)

### ISSUE THREAD

**Issue by outofmap** [NHNNEXT/2015-01-WEB-TOITOITOI#168]
총 갯수를 알면 페이지 갯수알고->더보기 필요 여부 결정할 수 있음!

**Comment by Kiboom** [comment]
따로 dear 테이블에 postNum 필드를 추가하지 않기로 하였습니다. 대신 PostDAO의 getDearList 메서드에서 postNum 정보를 보내주기로 하였습니다.
왜냐하면 dear 테이블이 postNum을 가지고 있으면, 특정 place별로 구분해서 postNum을 보내줄 수 없기 때문입니다.
