### ISSUE TITLE
새 글 등록시 ajax로 처리

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#22]

**Comment by hyoeun** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
이효은(hyoeun.lee@connect.o...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [2015-01-WEB-TOITOITOI] 새 글 등록시 ajax로 처리 (#22)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
이효은(hyoeun.lee@connect.o...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-10-05 10:00 ~ 2015-10-08 19:00 GMT +09:00]<br>개인 휴가로 부재중입니다. <br>급한 용무는 라인이나 NCS 메신저로 남겨주시면 <br>최대한 빨리 확인후 답변 드리겠습니다. 
--------------------------------------------
