### ISSUE TITLE
NudgeDAO.getNudgeList() 하면 nudgeid 가 모두 0으로 나옵니다

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#46]
https://github.com/NHNNEXT/2015-01-WEB-TOITOITOI/commit/93a43861d484e84415cf4a4ff02bfa41128cbea6#diff-f15dd7e67e7091f9de34992693cdb981R7
때문인듯 합니다.

**Comment by outofmap** [comment]
고쳤습니다.
