### ISSUE TITLE
post list에서 검색버튼을 누르면 상단바에 검색창이 뜨게 한다

### ISSUE THREAD

**Issue by Kiboom** [NHNNEXT/2015-01-WEB-TOITOITOI#48]
post list에서 검색버튼을 누르면 상단바에 검색창이 뜨게 한다.

![](http://i61.tinypic.com/2u3zmeq.png)

**Comment by helloheesu** [comment]
검색 기능이슈와 연결될 것 같아 직접 close하지는 않았다. 대략 구현은 해 봤음.
