### ISSUE TITLE
유도글이 길어서 넘친 부분을 애니메이션으로 처리한다

### ISSUE THREAD

**Issue by Kiboom** [NHNNEXT/2015-01-WEB-TOITOITOI#49]
유도글이 너무 길어서 input 박스를 넘어가면, 넘친 부분을 전광판 애니메이션으로 처리한다.

**Comment by helloheesu** [comment]
- placeholder는 실제 dom이 아니라 가상의 dom이다. 따라서 javascript에서 select 할 수 없고, scrollWidth등에도 영향을 끼치지 않는다.
- 그렇다면 각종 꼼수를 동원해 placeholder를 가장한 새로운 엘리먼트를 위에 덮어써야한다. 마크업 구조와 js코드가 모두 더러워질 것이다.
- 차라리 높이를 조금 높게 고정하고, 최대 글자수도 제한하는 건 어떨까?

**Comment by helloheesu** [comment]
변경된 요구사항 : 
- 스크롤 됐을 땐 text-ellipse
- focus 됐을 때 height를 키우기
