### ISSUE TITLE
개별 post 요청시 (브라우저, api) 주소 validation

### ISSUE THREAD

**Issue by helloheesu** [NHNNEXT/2015-01-WEB-TOITOITOI#91]
`/place/1/dear/뷰티토이/post/7` 이렇게 들어왔을 때
* `/dear/뷰티토이`가 `place/1` 밑에 없을 수도 있고,
* 있다하더라도 `post/7`가 그 밑에 속하지 않을 수 있어요.

**Comment by outofmap** [comment]
/dear/뷰티토이가 place/1 밑에 없을 수도 있고 ->  data not found
